/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "smartknob.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
// todo #error Regenerate this file with the current version of nanopb generator.
#endif

// todo PB_BIND(PB_FromSmartKnob, PB_FromSmartKnob, 2)


// todo PB_BIND(PB_ToSmartknob, PB_ToSmartknob, AUTO)


// todo PB_BIND(PB_Ack, PB_Ack, AUTO)


// todo PB_BIND(PB_Log, PB_Log, 2)


// todo PB_BIND(PB_SmartKnobState, PB_SmartKnobState, AUTO)


// todo PB_BIND(PB_SmartKnobConfig, PB_SmartKnobConfig, AUTO)


// todo PB_BIND(PB_RequestState, PB_RequestState, AUTO)


// todo PB_BIND(PB_PersistentConfiguration, PB_PersistentConfiguration, AUTO)


// todo PB_BIND(PB_MotorCalibration, PB_MotorCalibration, AUTO)


// todo PB_BIND(PB_StrainCalibration, PB_StrainCalibration, AUTO)



